### ISSUE TITLE
BNO055

### ISSUE THREAD

**Issue by kennibaz** [m9cd0n9ld/IMU-VR-Full-Body-Tracker#1]
Is it possible to substitute BNO085 with BNO055?

**Comment by m9cd0n9ld** [comment]
As long as the IMU sensor or AHRS algorithm can provide quaternion in ENU coordinate, any IMU sensor can be used, just need to do some minor modification in the Arduino sketch code. But for best result, it's better to use high quality AHRS output IMU such as BNO085, etc.

**Comment by kennibaz** [comment]
Thanks for your reply. The reason I’m asking about the substitute is bc
there is a huge shortage of bno085.
Could be mpu 6050 used as well?

**Comment by m9cd0n9ld** [comment]
I see mpu6050 can output quaternion, shouldn't be a problem.

**Comment by kennibaz** [comment]
Great, thanks!
