### ISSUE TITLE
Pose estimates from 6 IMUs 

### ISSUE THREAD

**Issue by NoLoPhe** [m9cd0n9ld/IMU-VR-Full-Body-Tracker#2]
Hi!

I made pose estimates from 6 IMUs based on the results of the paper TransPose.
I want it to work with VRchat. How do I do that?

I don't see documentation to send skeleton coordinates to Openvr.

Thankyou!

Link: https://twitter.com/Tn23008624/status/1494618444821839877

**Comment by m9cd0n9ld** [comment]
Dear @NoLoPhe , you need to create Steam VR driver that reads the skeleton coordinates data, then output them as steam tracker devices to Steam VR. You can refer to steamvr_openvr_driver directory for example.

**Comment by NoLoPhe** [comment]
@m9cd0n9ld Thanks for the quick response, I'll take a look at the code.
