### ISSUE TITLE
View Mirror

### ISSUE THREAD

**Issue by NoLoPhe** [m9cd0n9ld/IMU-VR-Full-Body-Tracker#3]
Hi!

I need my avatar to show in front of the mirror, how can I do that?

Thankyou!

Link: https://github.com/m9cd0n9ld/IMU-VR-Full-Body-Tracker/blob/main/media/preview_feet.gif

**Comment by m9cd0n9ld** [comment]
You can try [LIV](https://store.steampowered.com/app/755540/LIV/).

**Comment by NoLoPhe** [comment]
Thank you very much, you answer fast too!
