### ISSUE TITLE
Need help in understanding the code's logic

### ISSUE THREAD

**Issue by TparT** [m9cd0n9ld/IMU-VR-Full-Body-Tracker#4]
Hi there! Im looking into making a full body tracking suit for a school project and I found your repo which looks really nice.
Only problem is I cant figure out much about the order of the logic, like how and when do I set the tracker location, when is the data transmitted to SteamVR etc..

We could also move to a different chatting platform like Discord if that would make things easier.

So, if you could help me out and guide me through the code it would be very very appreciated :D

**Comment by m9cd0n9ld** [comment]
Hi @TparT,

If you are interested in algorithm behind it, you can just implement this [header](https://github.com/m9cd0n9ld/IMU-VR-Full-Body-Tracker/blob/main/imuFBTServerBackend/headers/kinematics.h) file to your project. It might not be the best solution for full body tracking.

**Comment by TparT** [comment]
Okay, I guess I missed the part where you need to enable the trackers in the 'Main settings' tab really down there. Thanks anyways for replying and trying to help :D
